
networks:
  SPARK_CLUSTER:
    driver: bridge
    name: SPARK_CLUSTER

services:
  spark-master:
    build:
      context: .
      dockerfile: ./spark-master/Dockerfile
    container_name: spark-master
    image: spark-cluster:version-1.0.0
    networks:
      - SPARK_CLUSTER
    ports:
      - "8888:8888"  # Jupyter Notebook
      - "7077:7077"  # Spark Master RPC Port
      - "8082:8080"  # Master Web UI
      # - "5572:5572" # rclone RC Port
    environment:
      - SPARK_MASTER_HOST=spark-master
      - SPARK_MASTER_URL=spark://spark-master:7077
    volumes:
      - /Users/anoopm/my_jupyter_project/Docker_setup/fat.jar:/app/setup/fat.jar
      - /Users/anoopm/my_jupyter_project/Scripts:/home/jovyan/Notebooks
      - /Users/anoopm/Documents/Local_Folder:/mnt
      - /Users/anoopm/Library/CloudStorage/OneDrive-Personal/Cloud_Documents:/data
      - /Users/anoopm/Documents/Spark_Work:/usr/local/spark/work
      - /Users/anoopm/my_jupyter_project/Docker_setup/spark-master:/usr/local/spark/conf
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080"]
      interval: 30s
      retries: 3
      start_period: 10s
      timeout: 10s

  spark-worker:
    build:
      context: .
      dockerfile: ./spark-worker/Dockerfile
    image: spark-worker:version1.0.0
    networks:
      - SPARK_CLUSTER
    depends_on:
      spark-master:
        condition: service_healthy
    environment:
      - SPARK_MASTER=spark://spark-master:7077
      - SPARK_WORKER_CORES=2
      - SPARK_WORKER_MEMORY=1G
    volumes:
      - /Users/anoopm/my_jupyter_project/Docker_setup/fat.jar:/app/setup/fat.jar
      - /Users/anoopm/my_jupyter_project/Scripts:/home/jovyan/Notebooks
      - /Users/anoopm/Documents/Local_Folder:/mnt
      - /Users/anoopm/Library/CloudStorage/OneDrive-Personal/Cloud_Documents:/data
      - /Users/anoopm/Documents/Spark_Work:/usr/local/spark/work
      - /Users/anoopm/my_jupyter_project/Docker_setup/spark-master/spark-defaults.json:${SPARK_HOME}/conf/spark-defaults.json
      - /Users/anoopm/my_jupyter_project/Docker_setup/spark-master/packages.txt:/usr/local/spark/conf/packages.txt
    ports:
      - "8081:8081"  # Worker Web UI
      - "7337:7337"  # Worker Communication Port